# Generated by Django 3.1 on 2023-02-08 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bidding_auction'),
        ('auctions', '0004_auto_20200902_0121'),
        ('auctions', '0002_auto_20200911_0907'),
    ]

    operations = [
    ]
